name: (BUILD)

on:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: pwsh
    
env:
  FORCE_COLOR: 3

jobs:
   Initialization:
    runs-on: [ windows-latest ]
    outputs:
      type: ${{ steps.ReadSettings.outputs.type }}
      source_branch: ${{ steps.ReadSettings.outputs.source_branch }}
      versions: ${{ steps.ReadSettings.outputs.VersionsJson }}
      environments: ${{ steps.ReadSettings.outputs.EnvironmentsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Initialize the workflow
        uses: fscpscollaborative/fscps.gh/WorkflowInitialize@v2.1
        id: init
        env:
          secrets: ${{ toJson(secrets) }}    

      - name: Read settings
        id: ReadSettings
        uses: fscpscollaborative/fscps.gh/ReadSettings@v2.1
          
      - name: Check for updates to FSC-PS system files
        uses: fscpscollaborative/fscps.gh/CheckForUpdates@v2.1
        continue-on-error: true
        with:
          type: ${{ steps.ReadSettings.outputs.type }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}

   Build:
    needs: [ Initialization ]
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    name: Build 
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Read settings
        uses: fscpscollaborative/fscps.gh/ReadSettings@v2.1
          
      - name: Read secrets
        uses: fscpscollaborative/fscps.gh/ReadSecrets@v2.1
        env:
          secrets: ${{ toJson(secrets) }}       
        with:
          settingsJson: ${{ env.Settings }}
          

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2.0.0
        with:
          nuget-version: 5.10.x    

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0   
        with:
          node-version: '18'    
          
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'     

      - name: Run pipeline
        uses: fscpscollaborative/fscps.gh/RunPipeline@v2.1
        id: runpipeline
        with:
          type: ${{ needs.Initialization.outputs.type}}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
      
      - name: Publish artifacts  
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.ARTIFACTS_PATH }}
          
   PostProcess: 
    if: ${{ !cancelled() }}
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    needs: [ Initialization,  Build ]
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Read settings
        id: ReadSettings
        uses: fscpscollaborative/fscps.gh/ReadSettings@v2.1
        
      - name: Read secrets
        uses: fscpscollaborative/fscps.gh/ReadSecrets@v2.1
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          settingsJson: ${{ env.Settings }}
          
      - name: Finalize the workflow
        id: PostProcess
        uses: fscpscollaborative/fscps.gh/WorkflowPostProcess@v2.1
        with:
          remove_current: ${{ needs.Initialization.outputs.environments == '' }}
          settingsJson: ${{ env.Settings }}
          secretsJson: ${{ env.RepoSecrets }}
